# Generated by Django 5.0.3 on 2024-03-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrammessage',
            old_name='text',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='date',
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
