# Generated by Django 5.0.3 on 2024-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_telegrammessage_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=127)),
                ('text_welcome', models.TextField(max_length=1500)),
            ],
        ),
    ]
