# Generated by Django 5.0.3 on 2024-03-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(default='Русский', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
