# Generated by Django 5.0.3 on 2024-03-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_users_language_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='chat_id',
            new_name='user_id',
        ),
    ]
