# Generated by Django 5.0.3 on 2024-03-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_chat_id_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
