# Generated by Django 5.0.3 on 2024-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_users_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='find_tour',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='imguider',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
