# Generated by Django 5.0.3 on 2024-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_language_find_tour_language_imguider'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='choose_day',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='days',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='months',
            field=models.CharField(max_length=1270, null=True),
        ),
    ]
