# Generated by Django 5.0.3 on 2024-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_language_choose_day_language_days_language_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='language',
            name='months',
            field=models.JSONField(default=list),
        ),
    ]
