# Generated by Django 5.0.3 on 2024-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_language_days_alter_language_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='contact_menu',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='contact_text',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
