# Generated by Django 5.0.3 on 2024-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_language_contact_menu_language_contact_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1270, null=True)),
                ('license', models.ImageField(upload_to='photos/')),
                ('language', models.CharField(max_length=1270, null=True)),
                ('price', models.CharField(max_length=1270, null=True)),
                ('durability', models.CharField(max_length=1270, null=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('number', models.CharField(max_length=1270, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='guide_durability',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='guide_language',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='guide_license',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='guide_name',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='guide_number',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='guide_photo',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='guide_price',
            field=models.CharField(max_length=1270, null=True),
        ),
    ]
