# Generated by Django 5.0.3 on 2024-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_guide_id_guide_guide_is_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ad',
            field=models.CharField(max_length=1270, null=True),
        ),
    ]
