# Generated by Django 5.0.3 on 2024-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_language_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='license',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
