# Generated by Django 5.0.3 on 2024-03-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_guide_license_alter_guide_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='license',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='photo',
        ),
    ]
