# Generated by Django 5.0.3 on 2024-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_guide_license_remove_guide_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='license',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
