# Generated by Django 5.0.3 on 2024-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_guide_license_guide_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='license',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
