# Generated by Django 5.0.3 on 2024-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_guide_license_alter_guide_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='license',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='photo',
        ),
        migrations.AddField(
            model_name='guide',
            name='license_g',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='guide',
            name='photo_g',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
