# Generated by Django 5.0.3 on 2024-03-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_remove_guide_license_remove_guide_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='license_g',
            field=models.ImageField(blank=True, upload_to='E:\\Python\\jaunt\\media'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo_g',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
