# Generated by Django 5.0.3 on 2024-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_guide_license_g_alter_guide_photo_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='license_g',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='photo_g',
        ),
        migrations.AddField(
            model_name='guide',
            name='license',
            field=models.ImageField(blank=True, upload_to='E:\\Python\\jaunt\\media\\media'),
        ),
        migrations.AddField(
            model_name='guide',
            name='photo',
            field=models.ImageField(blank=True, upload_to='E:\\Python\\jaunt\\media\\media'),
        ),
    ]
