# Generated by Django 5.0.3 on 2024-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_remove_guide_license_g_remove_guide_photo_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='license',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
