# Generated by Django 5.0.3 on 2024-04-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_alter_guide_license_alter_guide_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='back',
            field=models.CharField(max_length=1270, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='share_contant',
            field=models.CharField(max_length=1270, null=True),
        ),
    ]
